install:
	cp ANSI_C_UnitTest.h /usr/include/easy-c-unit.h
	cp CURunnerLinux.so /usr/lib/
	cp libeasy-c-unit.a /usr/lib/
	cp cunit_runner /usr/bin/
	mkdir -p /usr/share/doc/easy-c-unit/
	cp Readme.txt simple_vc_gcc.c /usr/share/doc/easy-c-unit/
